version: "3"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express
    environment:
      - "ME_CONFIG_BASICAUTH_USERNAME=millerp"
      - "ME_CONFIG_BASICAUTH_PASSWORD=81268445"
      - "ME_CONFIG_OPTIONS_EDITORTHEME=monokai"
    ports:
      - "8081:8081"
    links:
      - mongo